- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4832/workspace/MavenWebApp4/target/MavenWebApp4.war"
        dest: "/opt/tomcat/webapps/MavenWebApp4.war"
        remote_src: no
    - name:  Restart Tomcat
      systemd:
        name: tomcat
        state: restarted

